### ISSUE TITLE
Acceptance of Ownership Addition

### ISSUE THREAD

**Issue by joshuabailes** [18F/iaa-forms#4]
Need to add a link on https://pages.18f.gov/iaa-forms/ in item number 2. The actual attachment is listed below. Would like the page to have the actual text as well as explanation.

Explanation:
System Ownership
Whoever owns a government information system must accept the risk of operating that system. Most 18F engagements, regardless of business unit, require us to operate an information system for some period of time: whether in alpha, beta, or fully live status.

For Federal teams that support the mission of other Federal agencies, it can sometimes be unclear who must accept this risk.

At 18F, we require that all of our partners agree that for 18F owned systems, 18F will enforce a risk management framework and will grant the system’s authority to operate (ATO) based on 18F standards. If the system is transferred to the partner at later date, they will then need to issue a new ATO. This agreement provides the necessary clarity on roles and responsibilities for the system.

Actual text:
REQUESTING AGENCY

7600B, ATTACHMENT D
Acceptance of Ownership

I, [NAME], the Authorizing Official for [DEPT/AGENCY DIVISION/TEAM], hereby accept 18F/GSA’s authority to accept the risk of operating information systems under 18F/GSA’s control and created as a result of Interagency Agreement [NUMBER]. 18F/GSA’s authority is to determine the level of risk, select controls, test the system, grant an authority to operate, and to ensure compliance with all relevant laws and regulations.

18F/GSA will work independently to receive an authority to operate and will bear responsibility of technical work associated with the process.

---

Signature of [NAME + TITLE]

---

Date

**Comment by joshuabailes** [comment]
@jezhumble See above. Confirm this looks right. I'll do a pull request (total novice but we will see how it goes) once you confirm.

**Comment by jezhumble** [comment]
That looks great.

Just one mod: "At 18F, we require that all of our partners agree that for 18F owned systems" -> "At 18F, we require that all of our partners agree that for systems operated by 18F"

Confirmed.

**Comment by joshuabailes** [comment]
@andrewmaier any chance you could help me get this posted? Direct me somewhere to do it?
